name: arithmann
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies: 
  - cudatoolkit=11.3  
  - hydra-core
  - ipython
  - ipykernel
  - ipywidgets
  - notebook
  - pytorch::pytorch
  - pytorch::torchtext=0.12
  - torchmetrics
  - wandb

# to use the A5000 nodes a specific pytorch build compliant with CUDA drivers of the GPU needs to be installed

# local package
# -e .
