defaults:
        - run: slurm
        - data: maths
        - model: lstm
        - train: math_rnn
        - override hydra/hydra_logging: none
        - override hydra/job_logging: custom
        - _self_

hydra:
  run:
    dir: ../hydra/${hydra.job.name}/${now:%Y-%B-%d_%H-%M-%S}
